name: CLEAN ANON
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: CLEAN ANON
        run: |
          curl --request POST \
          --url 'https://www.blind.nib.gg/api/cron/anon' \
          --header 'Authorization: Bearer ${{ secrets.ACTION_KEY }}'
